NoLifeStory: NoLifeStory/NoLifeStory.cpp File Reference
NoLifeStory.cpp File Reference
#include "Global.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 7 of file NoLifeStory.cpp.
References NLS::console, NLS::Init(), NLS::Loop(), and NLS::Unload().
                                {//Not much to do here
    NLS::console = new NLS::Console();
    vector<string> strs(argv, argv+argc);
    //Actually run NLS here
    NLS::Init(strs);
    while (NLS::Loop()) {}
    NLS::Unload();
    delete NLS::console;
    return 0;
}