NoLifeStory: src/NoLifeStory/Utilities.h File Reference
Utilities.h File Reference
Defines
#define PI 3.1415926535897932384626433832795
#define degtorad 0.01745329251994329576923690768489
#define radtodeg 57.295779513082320876798154814105
Functions
string tostring (const double &t)
string tostring (const int &t)
string tostring (const int &t, const int &len)
double todouble (const string &t)
int toint (const string &t)
double sqr (const double &x)
double pdis (const double &x1, const double &y1, const double &x2, const double &y2)
double pdir (const double &x1, const double &y1, const double &x2, const double &y2)
double ldx (const double &len, const double &dir)
double ldy (const double &len, const double &dir)
double angdif (const double &angle1, const double &angle2)
double sign (const double &x)
bool exists (const string &name)
Define Documentation
#define degtorad 0.01745329251994329576923690768489
Definition at line 7 of file Utilities.h.
Referenced by ldx(), and ldy().
#define PI 3.1415926535897932384626433832795
Definition at line 6 of file Utilities.h.
Referenced by NLS::Back::Draw(), and NLS::Obj::Draw().
#define radtodeg 57.295779513082320876798154814105
Definition at line 8 of file Utilities.h.
Referenced by NLS::Back::Draw(), NLS::Obj::Draw(), and pdir().
Function Documentation
double angdif (const double & angle1, const double & angle2) [inline]
Definition at line 65 of file Utilities.h.
{
    return fmod(fmod(angle1-angle2, 360)+540, 360)-180;
}
bool exists (const string & name) [inline]
Definition at line 73 of file Utilities.h.
Referenced by NLS::WZ::Init().
{
    ifstream file(name);
    bool check = file.is_open();
    file.close();
    return check;
}
double ldx (const double & len, const double & dir) [inline]
Definition at line 57 of file Utilities.h.
References degtorad.
{
    return cos(dir*degtorad)*len;
}
double ldy (const double & len, const double & dir) [inline]
Definition at line 61 of file Utilities.h.
References degtorad.
{
    return sin(dir*degtorad)*len;
}
double pdir (const double & x1, const double & y1, const double & x2, const double & y2) [inline]
Definition at line 53 of file Utilities.h.
References radtodeg.
Referenced by NLS::Foothold::Load().
{
    return radtodeg*atan2(y2-y1, x2-x1);
}
double pdis (const double & x1, const double & y1, const double & x2, const double & y2) [inline]
Definition at line 49 of file Utilities.h.
References sqr().
Referenced by NLS::Foothold::Load().
{
    return sqrt(sqr(x1-x2)+sqr(y1-y2));
}
double sign (const double & x) [inline]
Definition at line 69 of file Utilities.h.
Referenced by NLS::_View::Step().
{
    return x>0?1:x<0?-1:0;
}
double sqr (const double & x) [inline]
Definition at line 45 of file Utilities.h.
Referenced by pdis().
{
    return x*x;
}
double todouble (const string & t) [inline]
Definition at line 29 of file Utilities.h.
Referenced by NLS::Node::operator=().
{
    stringstream ss;
    ss << t;
    double d;
    ss >> d;
    return d;
}
int toint (const string & t) [inline]
Definition at line 37 of file Utilities.h.
Referenced by NLS::Back::Load(), NLS::Foothold::Load(), and NLS::Node::operator=().
{
    stringstream ss;
    ss << t;
    int d;
    ss >> d;
    return d;
}
string tostring (const double & t) [inline]
Definition at line 10 of file Utilities.h.
Referenced by NLS::Graphics::Draw(), NLS::WZ::ExtendedProperty(), NLS::WZ::File(), NLS::Node::operator=(), and NLS::Node::operator[]().
{
    static char str[32];
    sprintf(str, "%f", t);
    return str;
}
string tostring (const int & t) [inline]
Definition at line 16 of file Utilities.h.
{
    static char str[32];
    sprintf(str, "%i", t);
    return str;
}
string tostring (const int & t, const int & len) [inline]
Definition at line 22 of file Utilities.h.
{
    stringstream ss;
    ss << t;
    string s = ss.str();
    return s.insert(0, len-s.size(), '0');
}