NoLifeStory: NoLifeStory/WZ.cpp File Reference
WZ.cpp File Reference
#include "Global.h"
#include "Keys.h"
Functions
void Decompress (uint32_t inLen, uint32_t outLen)
template<class T >
T Read (ifstream &file)
template<class T >
T Read (NLS::WZ::File *file)
int32_t ReadCInt (ifstream &file)
uint32_t ReadOffset (NLS::WZ::File *file)
string ReadEncString (ifstream &file)
void ReadEncFast (ifstream &file)
string ReadString (ifstream &file, uint32_t offset)
string ReadStringOffset (ifstream &file, uint32_t offset)
Variables
set< NLS::WZ::File * > Files
string Path
uint8_t * WZKey = 0
uint8_t BMSKey [0xFFFF]
uint8_t * WZKeys [] = {GMSKey, BMSKey}
uint8_t GMSKeyIV [4] = {0x4D, 0x23, 0xC7, 0x2B}
uint32_t OffsetKey = 0x581C3F6D
int16_t EncVersion
uint16_t Version
uint32_t VersionHash
uint8_t Buf1 [0x1000000]
uint8_t Buf2 [0x1000000]
Function Documentation
void Decompress (uint32_t inLen, uint32_t outLen)
Definition at line 24 of file WZ.cpp.
References Buf1, Buf2, and NLS::C().
Referenced by NLS::WZ::PNGProperty::Parse().
{
    int err = Z_OK;
    z_stream strm;
    strm.next_in = Buf2;
    strm.avail_in = inLen;
    strm.opaque = nullptr;
    strm.zfree = nullptr;
    strm.zalloc = nullptr;
    inflateInit(&strm);
    strm.next_out = Buf1;
    strm.avail_out = outLen;
    err = inflate(&strm, Z_NO_FLUSH);
    switch(err){
    case Z_OK:
    case Z_STREAM_END:
        break;
    default:
        NLS::C("ERROR") << "I hate zlib!" << endl;
        throw(273);
    }
    if (strm.total_out != outLen) {
        NLS::C("ERROR") << "I hate zlib!" << endl;
        throw(273);
    }
    inflateEnd(&strm);
}
template<class T > T Read (ifstream & file) [inline]
Definition at line 54 of file WZ.cpp.
{
    T v;
    file.read((char*)&v, sizeof(v));
    return v;
}
template<class T > T Read (NLS::WZ::File * file) [inline]
Definition at line 61 of file WZ.cpp.
References NLS::WZ::File::file.
{
    T v;
    file->file.read((char*)&v, sizeof(v));
    return v;
}
int32_t ReadCInt (ifstream & file) [inline]
Definition at line 67 of file WZ.cpp.
Referenced by NLS::WZ::Directory::Directory(), NLS::WZ::ExtendedProperty::ExtendedProperty(), NLS::WZ::File::File(), NLS::WZ::PNGProperty::PNGProperty(), and NLS::WZ::SubProperty::SubProperty().
{
    int8_t a = Read<int8_t>(file);
    if (a != -128) {
        return a;
    } else {
        int32_t b = Read<int32_t>(file);
        return b;
    }
}
void ReadEncFast (ifstream & file) [inline]
Definition at line 136 of file WZ.cpp.
Referenced by NLS::WZ::File::File().
{
    int8_t slen = Read<int8_t>(file);
    if (slen == 0) {return;}
    if (slen > 0) {
        int32_t len;
        if (slen == 127) {
            len = Read<int32_t>(file);
        } else {
            len = slen;
        }
        if (len <= 0) {return;}
        file.seekg(len*2, ios_base::cur);
    } else {
        int32_t len;
        if (slen == -128) {
            len = Read<int32_t>(file);
        } else {
            len = -slen;
        }
        if (len <= 0) {return;}
        file.seekg(len, ios_base::cur);
    }
}
string ReadEncString (ifstream & file) [inline]
Definition at line 89 of file WZ.cpp.
References WZKey.
Referenced by NLS::WZ::Directory::Directory(), NLS::WZ::ExtendedProperty::ExtendedProperty(), NLS::WZ::File::File(), NLS::WZ::Image::Parse(), ReadString(), and ReadStringOffset().
{
    int8_t slen = Read<int8_t>(file);
    if (slen == 0) {
        return string();
    } else if (slen > 0) {
        int32_t len;
        if (slen == 127) {
            len = Read<int32_t>(file);
        } else {
            len = slen;
        }
        if (len <= 0) {
            return string();
        }
        string s(len, '\0');
        uint16_t mask = 0xAAAA;
        for (int i = 0; i < len; i++) {
            uint16_t enc = Read<uint16_t>(file);
            enc ^= mask;
            enc ^= (WZKey[i*2+1]<<8)+WZKey[i*2];
            mask++;
            s[i] = enc;
        }
        return s;
    } else {
        int32_t len;
        if (slen == -128) {
            len = Read<int32_t>(file);
        } else {
            len = -slen;
        }
        if (len <= 0) {
            return string();
        }
        string s(len, '\0');
        uint8_t mask = 0xAA;
        for (int i = 0; i < len; i++) {
            uint8_t enc = Read<uint8_t>(file);
            enc ^= mask;
            enc ^= WZKey[i];
            mask++;
            s[i] = enc;
        }
        return s;
    }
}
uint32_t ReadOffset (NLS::WZ::File * file) [inline]
Definition at line 77 of file WZ.cpp.
References NLS::WZ::File::file, NLS::WZ::File::fileStart, OffsetKey, and VersionHash.
Referenced by NLS::WZ::Directory::Directory(), and NLS::WZ::File::File().
{
    uint32_t p = file->file.tellg();
    p = (p-file->fileStart)^0xFFFFFFFF;
    p *= VersionHash;
    p -= OffsetKey;
    p = (p<<(p&0x1F))|(p>>(32-p&0x1F));
    uint32_t more = Read<uint32_t>(file);
    p ^= more;
    p += file->fileStart*2;
    return p;
}
string ReadString (ifstream & file, uint32_t offset) [inline]
Definition at line 160 of file WZ.cpp.
References ReadEncString().
Referenced by NLS::WZ::SubProperty::SubProperty().
{
    uint8_t a = Read<uint8_t>(file);
    switch (a) {
    case 0x00:
    case 0x73:
        return ReadEncString(file);
    case 0x01:
    case 0x1B:
        {
            int32_t off = Read<int32_t>(file);
            offset += off;
            uint32_t p = file.tellg();
            file.seekg(offset);
            string s = ReadEncString(file);
            file.seekg(p);
            return s;
        }
    default:
        return string();
    }
}
string ReadStringOffset (ifstream & file, uint32_t offset) [inline]
Definition at line 182 of file WZ.cpp.
References ReadEncString().
Referenced by NLS::WZ::ExtendedProperty::ExtendedProperty().
{
    uint32_t p = file.tellg();
    file.seekg(offset);
    string s = ReadEncString(file);
    file.seekg(p);
    return s;
}
Variable Documentation
uint8_t BMSKey[0xFFFF]
Definition at line 13 of file WZ.cpp.
Referenced by NLS::WZ::Init().
uint8_t Buf1[0x1000000]
Definition at line 20 of file WZ.cpp.
Referenced by Decompress(), and NLS::WZ::PNGProperty::Parse().
uint8_t Buf2[0x1000000]
Definition at line 21 of file WZ.cpp.
Referenced by Decompress(), and NLS::WZ::PNGProperty::Parse().
int16_t EncVersion
Definition at line 17 of file WZ.cpp.
Referenced by NLS::WZ::File::File().
set<NLS::WZ::File*> Files
Definition at line 8 of file WZ.cpp.
Referenced by NLS::WZ::File::File().
uint8_t GMSKeyIV[4] = {0x4D, 0x23, 0xC7, 0x2B}
Definition at line 15 of file WZ.cpp.
uint32_t OffsetKey = 0x581C3F6D
Definition at line 16 of file WZ.cpp.
Referenced by ReadOffset().
string Path
Definition at line 9 of file WZ.cpp.
Referenced by NLS::WZ::File::File(), and NLS::WZ::Init().
uint16_t Version
Definition at line 18 of file WZ.cpp.
Referenced by NLS::WZ::File::File().
uint32_t VersionHash
Definition at line 19 of file WZ.cpp.
Referenced by NLS::WZ::File::File(), and ReadOffset().
uint8_t* WZKey = 0
Definition at line 12 of file WZ.cpp.
Referenced by NLS::WZ::File::File(), and ReadEncString().
uint8_t* WZKeys[] = {GMSKey, BMSKey}
Definition at line 14 of file WZ.cpp.
Referenced by NLS::WZ::File::File().