NoLifeStory: NLS::WorldServer Class Reference
NLS::WorldServer Class Reference
#include <WorldServer.h>
Static Public Member Functions
static void Start (int n=-1)
static void Shutdown (int n=-1)
Private Member Functions
WorldServer (int n)
void Loop ()
Private Attributes
bool done
sf::Thread * thread
Static Private Attributes
static map< int, WorldServer * > instances
Detailed Description
Definition at line 7 of file WorldServer.h.
Constructor & Destructor Documentation
NLS::WorldServer::WorldServer (int n) [private]
Definition at line 23 of file WorldServer.cpp.
References NLS::Loop().
Referenced by Start().
{
    done = false;
    thread = new sf::Thread([&](){this->Loop();});
    thread->Launch();
    cout << "INFO: WorldServer #" << n << " up and running" << endl;
}
Member Function Documentation
void NLS::WorldServer::Loop () [private]
Definition at line 30 of file WorldServer.cpp.
{
    while (!done) {
        sf::Sleep(0.1);
    }
}
void NLS::WorldServer::Shutdown (int n = -1) [static]
Definition at line 36 of file WorldServer.cpp.
Referenced by Start().
{
    if (n == -1) {
        for (auto it = instances.begin(); it != instances.end(); it++) {
            cout << "INFO: Shutting down WorldServer #" << it->first << endl;
            it->second->done = true;
            it->second->thread->Wait();
            delete it->second;
        }
        instances.clear();
    } else {
        auto it = instances.find(n);
        if (it == instances.end()) {
            cout << "WARNING: Unable to find WorldServer #" << n << endl;
        } else {
            cout << "INFO: Shutting down WorldServer #" << n << endl;
            it->second->done = true;
            it->second->thread->Wait();
            delete it->second;
            instances.erase(it);
        }
    }
}
void NLS::WorldServer::Start (int n = -1) [static]
Definition at line 9 of file WorldServer.cpp.
References instances, Shutdown(), and WorldServer().
{
    if (n == -1) {
        Start(0);
        Start(1);
    } else {
        cout << "INFO: Starting up WorldServer #" << n << endl;
        if (instances.find(n) != instances.end()) {
            cout << "WARNING: WorldServer #" << n << " already exists!" << endl;
            Shutdown(n);
        }
        instances[n] = new WorldServer(n);
    }
}
Member Data Documentation
bool NLS::WorldServer::done [private]
Definition at line 14 of file WorldServer.h.
map< int, NLS::WorldServer * > NLS::WorldServer::instances [static, private]
Definition at line 16 of file WorldServer.h.
Referenced by Start().
sf::Thread* NLS::WorldServer::thread [private]
Definition at line 15 of file WorldServer.h.
The documentation for this class was generated from the following files:
src/NoLifeServer/WorldServer.h
src/NoLifeServer/WorldServer.cpp