NoLifeStory: NLS::WZ::Directory Class Reference
NLS::WZ::Directory Class Reference
#include <WZ.h>
Public Member Functions
Directory (File *file, Node &n)
Public Attributes
File * file
Detailed Description
Definition at line 65 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::Directory::Directory (File * file, Node & n)
Definition at line 222 of file WZ.cpp.
References NLS::WZ::File::file, NLS::WZ::Header::fileStart, NLS::Node::g(), NLS::WZ::File::head, ReadCInt(), ReadEncString(), and ReadOffset().
{
    int32_t count = ReadCInt(file->file);
    set<pair<string, uint32_t>> dirs;
    for (int i = 0; i < count; i++) {
        string name;
        uint8_t type = Read<uint8_t>(file);
        if (type == 1) {
            file->file.seekg(10, ios_base::cur);
            continue;
        } else if (type == 2) {
            int32_t s = Read<int32_t>(file);
            uint32_t p = file->file.tellg();
            file->file.seekg(file->head->fileStart+s);
            type = Read<uint8_t>(file);
            name = ReadEncString(file->file);
            file->file.seekg(p);
        } else if (type == 3) {
            name = ReadEncString(file->file);
        } else if (type == 4) {
            name = ReadEncString(file->file);
        } else {
            continue;
        }
        int32_t fsize = ReadCInt(file->file);
        int32_t checksum = ReadCInt(file->file);
        uint32_t offset = ReadOffset(file);
        if (type == 3) {
            dirs.insert(pair<string, uint32_t>(name, offset));
        } else {
            name.erase(name.size()-4);
            new Image(file, n.g(name), offset);
        }
    }
    for (auto it = dirs.begin(); it != dirs.end(); it++) {
        file->file.seekg(it->second);
        new Directory(file, n.g(it->first));
    }
    delete this;
}
Member Data Documentation
File* NLS::WZ::Directory::file
Definition at line 68 of file WZ.h.
The documentation for this class was generated from the following files:
NoLifeStory/WZ.h
NoLifeStory/WZ.cpp