NoLifeStory: NLS::WZ::File Class Reference
NLS::WZ::File Class Reference
#include <WZ.h>
Public Member Functions
File (const string &name)
File (const string &name, bool beta)
uint32_t Hash (uint16_t enc, uint16_t real)
Public Attributes
ifstream file
string ident
uint64_t fileSize
uint32_t fileStart
string copyright
Detailed Description
Definition at line 33 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::File::File (const string & name)
Definition at line 214 of file WZ.cpp.
References NLS::C(), copyright, EncVersion, file, Files, fileSize, fileStart, NLS::Node::g(), ident, Path, and NLS::WZ::Top.
{
    string filename = Path+name+".wz";
    file.open(filename, file.in|file.binary);
    C("WZ") << "Loading file: " << filename << endl;
    if (!file.is_open()) {
        C("ERROR") << "Failed to load WZ file" << endl;
        throw(273);
    }
    Files.insert(this);
    ident.resize(4);
    file.read(const_cast<char*>(ident.c_str()), 4);
    fileSize = Read<uint64_t>(file);
    fileStart = Read<uint32_t>(file);
    file >> copyright;
    file.seekg(fileStart);
    int16_t eversion = Read<int16_t>(file);
    if (eversion != EncVersion) {
        C("ERROR") << "Version of WZ file does not match existing files" << endl;
    }
    new Directory(this, Top.g(name));
}
NLS::WZ::File::File (const string & name, bool beta)
Definition at line 235 of file WZ.cpp.
References NLS::C(), EncVersion, Files, NLS::Node::g(), Path, ReadCInt(), ReadEncFast(), ReadEncString(), ReadOffset(), NLS::WZ::Top, Version, VersionHash, WZKey, and WZKeys.
                                             {//TODO: Finish this!
    string filename = Path+name+".wz";
    file.open(filename, file.in|file.binary);
    C("WZ") << "Loading file: " << filename << endl;
    if (!file.is_open()) {
        C("ERROR") << "Failed to load WZ file" << endl;
        throw(273);
    }
    Files.insert(this);
    ident.resize(4);
    file.read(const_cast<char*>(ident.c_str()), 4);
    fileSize = Read<uint64_t>(file);
    fileStart = Read<uint32_t>(file);
    file >> copyright;
    file.seekg(fileStart);
    EncVersion = Read<int16_t>(file);
    int32_t count = ReadCInt(file);
    uint32_t c = 0;
    for (int k = 0; k < count; k++) {
        uint8_t type = Read<uint8_t>(file);
        if (type == 3) {
            ReadEncFast(file);
            ReadCInt(file);
            ReadCInt(file);
            Read<uint32_t>(file);
            continue;
        } else if (type == 4) {
            ReadEncFast(file);
            ReadCInt(file);
            ReadCInt(file);
            c = file.tellg();
            break;
        } else {
            C("ERROR") << "Malformed WZ structure" << endl;
            throw(273);
        }
    }
    if (c == 0) {
        C("ERROR") << "Unable to find a top level .img for hash verification" << endl;
    }
    for (uint8_t j = 0; j < 2; j++) {
        WZKey = WZKeys[j];
        for (Version = 0; Version < 256; Version++) {
            VersionHash = Hash(EncVersion, Version);
            if (VersionHash) {
                file.clear();
                file.seekg(c);
                uint32_t offset = ReadOffset(this);
                if (offset > fileSize) {
                    continue;
                }
                file.seekg(offset);
                uint8_t a = Read<uint8_t>(file);
                if(a != 0x73) {
                    continue;
                }
                string s = ReadEncString(file);
                if (s != "Property") {
                    continue;
                }
                C("WZ") << "Detected WZ version: " << Version << endl;
                goto wzdone;
            }
        }
    }
    C("ERROR") << "Unable to determine WZ version" << endl;
    throw(273);
    wzdone:
    file.seekg(fileStart+2);
    if (beta) {
        new Directory(this, Top);
    } else {
        new Directory(this, Top.g(name));
    }
}
Member Function Documentation
uint32_t NLS::WZ::File::Hash (uint16_t enc, uint16_t real)
Definition at line 311 of file WZ.cpp.
References tostring().
{
    string s = tostring(real);
    int l = s.size();
    uint32_t hash = 0;
    for (int i = 0; i < l; i++) {
        hash = 32*hash+s[i]+1;
    }
    uint32_t result = 0xFF^(hash>>24)^(hash<<8>>24)^(hash<<16>>24)^(hash<<24>>24);
    if (result == enc) {
        return hash;
    } else {
        return 0;
    }
}
Member Data Documentation
string NLS::WZ::File::copyright
Definition at line 42 of file WZ.h.
Referenced by File().
ifstream NLS::WZ::File::file
Definition at line 37 of file WZ.h.
Referenced by NLS::WZ::Directory::Directory(), NLS::WZ::ExtendedProperty::ExtendedProperty(), File(), NLS::WZ::PNGProperty::PNGProperty(), Read(), ReadOffset(), and NLS::WZ::SubProperty::SubProperty().
uint64_t NLS::WZ::File::fileSize
Definition at line 40 of file WZ.h.
Referenced by File().
uint32_t NLS::WZ::File::fileStart
Definition at line 41 of file WZ.h.
Referenced by NLS::WZ::Directory::Directory(), File(), and ReadOffset().
string NLS::WZ::File::ident
Definition at line 39 of file WZ.h.
Referenced by File().
The documentation for this class was generated from the following files:
NoLifeStory/WZ.h
NoLifeStory/WZ.cpp