NoLifeStory: NLS::LoginServer Class Reference
NLS::LoginServer Class Reference
#include <LoginServer.h>
Static Public Member Functions
static void Start ()
static void Shutdown ()
Private Member Functions
LoginServer ()
void Loop ()
Private Attributes
bool done
sf::Thread * thread
sf::TcpListener listener
Static Private Attributes
static LoginServer * instance = nullptr
Detailed Description
Definition at line 7 of file LoginServer.h.
Constructor & Destructor Documentation
NLS::LoginServer::LoginServer () [private]
Definition at line 18 of file LoginServer.cpp.
References NLS::Loop().
Referenced by Start().
{
    done = false;
    listener.SetBlocking(false);
    if (listener.Listen(8484) == sf::Socket::Error) {
        cerr << "ERROR: LoginServer failed to listen on port 8484" << endl;
        throw(273);
    }
    thread = new sf::Thread([&](){this->Loop();});
    thread->Launch();
    cout << "INFO: LoginServer up and listening on port 8484" << endl;
}
Member Function Documentation
void NLS::LoginServer::Loop () [private]
Definition at line 30 of file LoginServer.cpp.
{
    while (!done) {
        static sf::TcpSocket* next(new sf::TcpSocket());
        if (listener.Accept(*next) == sf::Socket::Done) {
            cout << "INFO: Player connected from " << next->GetRemoteAddress() << ":" << next->GetRemotePort() << endl;
            //Do stuff with next
            next = new sf::TcpSocket();
        }
        sf::Sleep(0.1);
    }
}
void NLS::LoginServer::Shutdown () [static]
Definition at line 42 of file LoginServer.cpp.
Referenced by Start().
{
    cout << "INFO: Shutting down LoginServer" << endl;
    instance->done = true;
    instance->thread->Wait();
    delete instance;
    instance = nullptr;
}
void NLS::LoginServer::Start () [static]
Definition at line 9 of file LoginServer.cpp.
References instance, LoginServer(), and Shutdown().
{
    if (instance != nullptr) {
        cout << "WARNING: Instance of LoginServer already exists!" << endl;
        Shutdown();
    }
    cout << "INFO: Starting up LoginServer" << endl;
    instance = new LoginServer();
}
Member Data Documentation
bool NLS::LoginServer::done [private]
Definition at line 14 of file LoginServer.h.
NLS::LoginServer * NLS::LoginServer::instance = nullptr [static, private]
Definition at line 17 of file LoginServer.h.
Referenced by Start().
sf::TcpListener NLS::LoginServer::listener [private]
Definition at line 16 of file LoginServer.h.
sf::Thread* NLS::LoginServer::thread [private]
Definition at line 15 of file LoginServer.h.
The documentation for this class was generated from the following files:
src/NoLifeServer/LoginServer.h
src/NoLifeServer/LoginServer.cpp