NoLifeStory: NLS::WZ::PNGProperty Class Reference
NLS::WZ::PNGProperty Class Reference
#include <WZ.h>
Public Member Functions
PNGProperty (File *file, Sprite spr)
void Parse ()
Public Attributes
File * file
Sprite sprite
int32_t format
uint8_t format2
int32_t length
uint32_t offset
Detailed Description
Definition at line 65 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::PNGProperty::PNGProperty (File * file, Sprite spr)
Definition at line 507 of file WZ.cpp.
References NLS::C(), NLS::Sprite::data, NLS::WZ::File::file, NLS::SpriteData::loaded, and ReadCInt().
{
    this->file = file;
    sprite = spr;
    sprite.data->loaded = false;
    sprite.data->width = ReadCInt(file->file);
    sprite.data->height = ReadCInt(file->file);
    uint32_t w, h;
    for (w = 1; w < sprite.data->width; w <<= 1) {}
    for (h = 1; h < sprite.data->height; h <<= 1) {}
    sprite.data->twidth = (float)sprite.data->width/w;
    sprite.data->theight = (float)sprite.data->height/h;
    format = ReadCInt(file->file);
    format2 = Read<uint8_t>(file);
    file->file.seekg(4, ios_base::cur);
    length = Read<int32_t>(file);
    if (length <= 0) {
        C("ERROR") << "What sort of shit is this?" << endl;
        throw(273);
    }
    offset = file->file.tellg();
    offset++;
}
Member Function Documentation
void NLS::WZ::PNGProperty::Parse ()
Definition at line 530 of file WZ.cpp.
References Buf1, Buf2, NLS::C(), and Decompress().
{
    file->file.seekg(offset);
    file->file.read((char*)Buf2, length);
    int32_t f = format+format2;
    glGenTextures(1, &sprite.data->texture);
    glBindTexture(GL_TEXTURE_2D, sprite.data->texture);
    switch (f) {
    case 1:
        {
            uint32_t len = 2*sprite.data->width*sprite.data->height;
            Decompress(length, len);
            for (uint32_t i = 0; i < len; i++) {
                Buf2[i*2] = (Buf1[i]&0x0F)|((Buf1[i]&0x0F)<<4);
                Buf2[i*2+1] = (Buf1[i]&0xF0)|((Buf1[i]&0xF0)>>4);
            }
            glTexImage2D(GL_TEXTURE_2D, 0, 4, sprite.data->width, sprite.data->height, 0, GL_BGRA, GL_UNSIGNED_BYTE, Buf2);
            break;
        }
    case 2:
        {
            uint32_t len = 4*sprite.data->width*sprite.data->height;
            Decompress(length, len);
            glTexImage2D(GL_TEXTURE_2D, 0, 4, sprite.data->width, sprite.data->height, 0, GL_BGRA, GL_UNSIGNED_BYTE, Buf1);
            break;
        }
    case 513:
        {
            uint32_t len = 2*sprite.data->width*sprite.data->height;
            Decompress(length, len);
            glTexImage2D(GL_TEXTURE_2D, 0, 4, sprite.data->width, sprite.data->height, 0, GL_BGR, GL_UNSIGNED_SHORT_5_6_5, Buf1);
            break;
        }
    case 517:
        {
            uint32_t len = sprite.data->width*sprite.data->height/128;
            Decompress(length, len);
            uint32_t t = 0;
            for (uint32_t i = 0; i < len; i++) {
                for (uint8_t j = 0; j < 8; j++) {
                    uint8_t b = ((Buf1[i]&(0x01<<(7-j)))>>(7-j))*0xFF;
                    for (uint8_t k = 0; k < 16; k++) {
                        Buf2[t] = b;
                        Buf2[t+1] = b;
                        Buf2[t+2] = b;
                        Buf2[t+3] = 0xFF;
                        t += 4;
                    }
                }
                glTexImage2D(GL_TEXTURE_2D, 0, 4, sprite.data->width, sprite.data->height, 0, GL_RGBA, GL_UNSIGNED_BYTE, Buf2);
            }
            break;
        }
    default:
        C("ERROR") << "Unknown sprite format" << endl;
        throw(273);
    }
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
    sprite.data->loaded = true;
}
Member Data Documentation
File* NLS::WZ::PNGProperty::file
Definition at line 69 of file WZ.h.
int32_t NLS::WZ::PNGProperty::format
Definition at line 71 of file WZ.h.
uint8_t NLS::WZ::PNGProperty::format2
Definition at line 72 of file WZ.h.
int32_t NLS::WZ::PNGProperty::length
Definition at line 73 of file WZ.h.
uint32_t NLS::WZ::PNGProperty::offset
Definition at line 74 of file WZ.h.
Sprite NLS::WZ::PNGProperty::sprite
Definition at line 70 of file WZ.h.
The documentation for this class was generated from the following files:
NoLifeStory/WZ.h
NoLifeStory/WZ.cpp