NoLifeStory: NLS::WZ::ExtendedProperty Class Reference
NLS::WZ::ExtendedProperty Class Reference
#include <WZ.h>
Public Member Functions
ExtendedProperty (File *file, Node &n, uint32_t offset, uint32_t eob)
Detailed Description
Definition at line 91 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::ExtendedProperty::ExtendedProperty (File * file, Node & n, uint32_t offset, uint32_t eob)
Definition at line 336 of file WZ.cpp.
References NLS::C(), NLS::Endl, NLS::WZ::File::file, NLS::Node::g(), ReadCInt(), ReadEncString(), and ReadStringOffset().
{
    string name;
    uint8_t a = Read<uint8_t>(file);
    if (a == 0x1B) {
        int32_t inc = Read<int32_t>(file);
        uint32_t pos = offset+inc;
        uint32_t p = file->file.tellg();
        file->file.seekg(pos);
        name = ReadEncString(file->file);
        file->file.seekg(p);
    } else {
        name = ReadEncString(file->file);
    }
    if (name == "Property") {
        file->file.seekg(2, ios_base::cur);
        new SubProperty(file, n, offset);
    } else if (name == "Canvas") {
        file->file.seekg(1, ios_base::cur);
        uint8_t b = Read<uint8_t>(file);
        if (b == 1) {
            file->file.seekg(2, ios_base::cur);
            new SubProperty(file, n, offset);
        }
        //TODO: Do something with the png property
    } else if (name == "Shape2D#Vector2D") {
        n.g("x") = ReadCInt(file->file);
        n.g("y") = ReadCInt(file->file);
    } else if (name == "Shape2D#Convex2D") {
        int32_t ec = ReadCInt(file->file);
        for (int i = 0; i < ec; i++) {
            new ExtendedProperty(file, n.g(name), offset, eob);
        }
    } else if (name == "Sound_DX8") {
        //TODO: Do something with the mp3 property
    } else if (name == "UOL") {
        file->file.seekg(1, ios_base::cur);
        uint8_t b = Read<uint8_t>(file);
        switch (b) {
        case 0:
            n.g(name) = string("|UOL|")+ReadEncString(file->file);
            break;
        case 1:
            {
                uint32_t off = Read<uint32_t>(file);
                n.g(name) = string("|UOL|")+ReadStringOffset(file->file, offset+off);
                break;
            }
        default:
            C("ERROR") << "Unknown UOL type" << Endl;
            throw(273);
        }
    } else {
        C("ERROR") << "Unknown ExtendedProperty type" << Endl;
        throw(273);
    }
    delete this;
}
The documentation for this class was generated from the following files:
NoLifeStory/WZ.h
NoLifeStory/WZ.cpp