NoLifeStory: NLS::AniSprite Class Reference
NLS::AniSprite Class Reference
#include <AniSprite.h>
Public Member Functions
AniSprite ()
void Set (class Node n)
void Draw (int x, int y, bool flipped=false, float rotation=0)
void Step ()
Public Attributes
Node n
Node f
int delay
int frame
bool repeat
float a
Detailed Description
Definition at line 7 of file AniSprite.h.
Constructor & Destructor Documentation
NLS::AniSprite::AniSprite ()
Definition at line 7 of file AniSprite.cpp.
References delay, frame, and repeat.
{
    frame = 0;
    delay = 0;
    repeat = true;
}
Member Function Documentation
void NLS::AniSprite::Draw (int x, int y, bool flipped = false, float rotation = 0)
Definition at line 21 of file AniSprite.cpp.
References NLS::Sprite::Draw().
{
    if (!n) {
        return;
    }
    Sprite s = f;
    s.Draw(x, y, flipped, a, rotation);
}
void NLS::AniSprite::Set (class Node n)
Definition at line 13 of file AniSprite.cpp.
Referenced by NLS::Back::Load(), and NLS::Obj::Load().
{
    frame = 0;
    delay = 0;
    this->n = n;
    f = n[0];
    a = 1;
}
void NLS::AniSprite::Step ()
Definition at line 29 of file AniSprite.cpp.
References NLS::_Time::delta, and NLS::Time.
{
    if (!n) {
        return;
    }
    delay += Time.delta;
    int d = f["delay"];
    if (d == 0) {
        d = 100;
    }
    if (delay > d) {
        delay  = 0;
        frame++;
        if (!n[frame]) {
            if (repeat) {
                frame = 0;
            } else {
                frame--;
            }
        }
        f = n[frame];
    }
    if (f["a0"] && (!repeat || f["a1"])) {
            double a0 = f["a0"];
            double a1 = f["a1"];
            a = (a0-(a0-a1)*delay/d)/255;
    }
}
Member Data Documentation
float NLS::AniSprite::a
Definition at line 17 of file AniSprite.h.
int NLS::AniSprite::delay
Definition at line 14 of file AniSprite.h.
Referenced by AniSprite().
Node NLS::AniSprite::f
Definition at line 13 of file AniSprite.h.
int NLS::AniSprite::frame
Definition at line 15 of file AniSprite.h.
Referenced by AniSprite().
Node NLS::AniSprite::n
Definition at line 13 of file AniSprite.h.
bool NLS::AniSprite::repeat
Definition at line 16 of file AniSprite.h.
Referenced by AniSprite(), and NLS::Obj::Load().
The documentation for this class was generated from the following files:
src/NoLifeStory/AniSprite.h
src/NoLifeStory/AniSprite.cpp