NoLifeStory: NLS::Node Class Reference
NLS::Node Class Reference
#include <WZ.h>
Public Member Functions
Node ()
Node (const Node &)
Node & operator= (const Node &)
Node & operator[] (const string &)
Node & operator[] (const char[])
Node & operator[] (const int &)
Node & g (const string &)
map< string, Node >::iterator Begin ()
map< string, Node >::iterator End ()
operator bool ()
operator string ()
operator double ()
operator int ()
operator Sprite ()
Node & operator= (const string &)
Node & operator= (const double &)
Node & operator= (const int &)
Public Attributes
class NodeData * data
Detailed Description
Definition at line 38 of file WZ.h.
Constructor & Destructor Documentation
NLS::Node::Node ()
Definition at line 612 of file WZ.cpp.
              {
    data = 0;
}
NLS::Node::Node (const Node & other)
Definition at line 616 of file WZ.cpp.
References data.
{
    data = other.data;
}
Member Function Documentation
map< string, NLS::Node >::iterator NLS::Node::Begin ()
Definition at line 664 of file WZ.cpp.
Referenced by NLS::Back::Load(), NLS::Portal::Load(), and NLS::Foothold::Load().
{
    assert(data);
    return data->children.begin();
}
map< string, NLS::Node >::iterator NLS::Node::End ()
Definition at line 669 of file WZ.cpp.
Referenced by NLS::Back::Load(), NLS::Tile::Load(), NLS::Portal::Load(), NLS::Obj::Load(), and NLS::Foothold::Load().
{
    assert(data);
    return data->children.end();
}
NLS::Node & NLS::Node::g (const string & key)
Definition at line 655 of file WZ.cpp.
References data, NLS::NodeData::name, and NLS::NodeData::parent.
Referenced by NLS::WZ::ExtendedProperty(), NLS::WZ::File(), and NLS::WZ::SubProperty().
{
    assert(data);
    Node& n = data->children[key];
    n.data = new NodeData();
    n.data->parent = *this;
    n.data->name = key;
    return n;
}
NLS::Node::operator bool ()
Definition at line 674 of file WZ.cpp.
                       {
    return (bool)data;
}
NLS::Node::operator double ()
Definition at line 685 of file WZ.cpp.
{
    if (!data) {
        return 0;
    }
    return data->floatValue;
}
NLS::Node::operator int ()
Definition at line 692 of file WZ.cpp.
                      {
    if (!data) {
        return 0;
    }
    return data->intValue;
}
NLS::Node::operator Sprite ()
NLS::Node::operator string ()
Definition at line 678 of file WZ.cpp.
{
    if (!data) {
        return string();
    }
    return data->stringValue;
}
NLS::Node & NLS::Node::operator= (const Node & other)
Definition at line 620 of file WZ.cpp.
References data.
{
    data = other.data;
    return *this;
}
NLS::Node & NLS::Node::operator= (const string & v)
Definition at line 706 of file WZ.cpp.
References todouble(), and toint().
{
    assert(data);
    data->intValue = toint(v);
    data->floatValue = todouble(v);
    data->stringValue = v;
    return *this;
}
NLS::Node & NLS::Node::operator= (const double & v)
Definition at line 714 of file WZ.cpp.
References tostring().
{
    assert(data);
    data->intValue = v;
    data->floatValue = v;
    data->stringValue = tostring(v);
    return *this;
}
NLS::Node & NLS::Node::operator= (const int & v)
Definition at line 722 of file WZ.cpp.
References tostring().
{
    assert(data);
    data->intValue = v;
    data->floatValue = v;
    data->stringValue = tostring(v);
    return *this;
}
NLS::Node & NLS::Node::operator[] (const string & key)
Definition at line 625 of file WZ.cpp.
References NLS::WZ::Empty, and NLS::WZ::Image::Parse().
{
    if (data) {
        if (data->image) {
            WZ::Image *img = data->image;
            data->image = 0;
            img->Parse();
        }
        return data->children[key];
    } else {
        return WZ::Empty;
    }
}
NLS::Node & NLS::Node::operator[] (const char key[])
Definition at line 638 of file WZ.cpp.
References NLS::WZ::Empty, and NLS::WZ::Image::Parse().
{
    if (data) {
        if (data->image) {
            WZ::Image *img = data->image;
            data->image = 0;
            img->Parse();
        }
        return data->children[key];
    } else {
        return WZ::Empty;
    }
}
NLS::Node & NLS::Node::operator[] (const int & key)
Definition at line 651 of file WZ.cpp.
References tostring().
{
    return (*this)[tostring(key)];
}
Member Data Documentation
class NodeData* NLS::Node::data
Definition at line 57 of file WZ.h.
Referenced by NLS::WZ::ExtendedProperty(), NLS::WZ::File(), g(), NLS::WZ::Image::Image(), NLS::WZ::Init(), Node(), NLS::Sound::operator=(), operator=(), NLS::WZ::Image::Parse(), and NLS::WZ::SoundProperty::SoundProperty().
The documentation for this class was generated from the following files:
src/NoLifeStory/WZ.h
src/NoLifeStory/WZ.cpp