NoLifeStory: NLS::WZ::SubProperty Class Reference
NLS::WZ::SubProperty Class Reference
#include <WZ.h>
Public Member Functions
SubProperty (File *file, Node n, uint32_t offset)
Detailed Description
Definition at line 57 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::SubProperty::SubProperty (File * file, Node n, uint32_t offset)
Definition at line 403 of file WZ.cpp.
References NLS::C(), NLS::WZ::File::file, NLS::Node::g(), ReadCInt(), and ReadString().
{
    int32_t count = ReadCInt(file->file);
    for (int i = 0; i < count; i++) {
        string name = ReadString(file->file, offset);
        uint8_t a = Read<uint8_t>(file);
        switch (a) {
        case 0x00:
            n.g(name);
            break;
        case 0x0B:
        case 0x02:
            n.g(name) = Read<uint16_t>(file);
            break;
        case 0x03:
            n.g(name) = ReadCInt(file->file);
            break;
        case 0x04:
            if (Read<uint8_t>(file) == 0x80) {
                n.g(name) = Read<float>(file);
            }
            break;
        case 0x05:
                n.g(name) = Read<double>(file);;
                break;
        case 0x08:
            n.g(name) = ReadString(file->file, offset);
            break;
        case 0x09:
            {
                uint32_t temp = Read<uint32_t>(file);
                temp += file->file.tellg();
                new ExtendedProperty(file, n.g(name), offset, temp);
                file->file.seekg(temp);
                break;
            }
        default:
            C("ERROR") << "Unknown Property type" << endl;
            throw(273);
        }
    }
    delete this;
}
The documentation for this class was generated from the following files:
NoLifeStory/WZ.h
NoLifeStory/WZ.cpp