NoLifeStory: NLS::WZ::Image Class Reference
NLS::WZ::Image Class Reference
#include <WZ.h>
Public Member Functions
Image (ifstream *file, Node n, uint32_t offset)
void Parse ()
Public Attributes
Node n
uint32_t offset
ifstream * file
Detailed Description
Definition at line 63 of file WZ.h.
Constructor & Destructor Documentation
NLS::WZ::Image::Image (ifstream * file, Node n, uint32_t offset)
Definition at line 350 of file WZ.cpp.
References NLS::Node::data, file, NLS::NodeData::image, n, and offset.
{
    this->n = n;
    n.data->image = this;
    this->offset = offset;
    this->file = file;
}
Member Function Documentation
void NLS::WZ::Image::Parse ()
Definition at line 357 of file WZ.cpp.
References NLS::C(), NLS::NodeData::children, NLS::Sprite::data, NLS::Node::data, NLS::NodeData::floatValue, NLS::NodeData::image, NLS::NodeData::intValue, NLS::NodeData::parent, ReadEncString(), NLS::NodeData::sprite, NLS::NodeData::stringValue, and NLS::WZ::SubProperty().
Referenced by NLS::Node::operator[]().
                       {
    file->seekg(offset);
    uint8_t a = Read<uint8_t>(file);
    if (a != 0x73) {
        C("WZ") << "Invalid WZ image!" << endl;
        throw(273);
    }
    string s = ReadEncString(file);
    if (s != "Property") {
        C("WZ") << "Invalid WZ image!" << endl;
        throw(273);
    }
    uint16_t b = Read<uint16_t>(file);
    if (b != 0) {
        C("WZ") << "Invalid WZ image!" << endl;
        throw(273);
    }
    SubProperty(file, n, offset);
    function <void(Node)> Resolve = [&Resolve](Node n) {
        if (n.data->children.find("UOL") != n.data->children.end()) {
            string s = n["UOL"];
            string str;
            vector <string> parts;
            for (int i = 0; i < s.size(); i++) {
                if (s[i] == '/') {
                    parts.push_back(str);
                    str = "";
                } else {
                    str.push_back(s[i]);
                }
            }
            parts.push_back(str);
            Node nn = n.data->parent;
            for (auto it = parts.begin(); it != parts.end(); it++) {
                if (!nn) {
                    break;
                }
                if (*it == "..") {
                    nn = nn.data->parent;
                } else {
                    nn = nn[*it];
                }
            }
            if (nn) {
                n.data->children = nn.data->children;
                n.data->floatValue = nn.data->floatValue;
                n.data->intValue = nn.data->intValue;
                n.data->stringValue = nn.data->stringValue;
                n.data->sprite = nn.data->sprite;
                n.data->image = nn.data->image;
            }
        } else {
            for (auto it = n.Begin(); it != n.End(); it++) {
                if (it->second.data) {
                    Resolve(it->second);
                }
            }
        }
    };
    Resolve(n);
    delete this;
}
Member Data Documentation
ifstream* NLS::WZ::Image::file
Definition at line 69 of file WZ.h.
Referenced by Image().
Node NLS::WZ::Image::n
Definition at line 67 of file WZ.h.
Referenced by Image().
uint32_t NLS::WZ::Image::offset
Definition at line 68 of file WZ.h.
Referenced by Image().
The documentation for this class was generated from the following files:
src/NoLifeStory/WZ.h
src/NoLifeStory/WZ.cpp