NoLifeStory: NLS::_Time Class Reference
NLS::_Time Class Reference
#include <Time.h>
Public Member Functions
void Reset ()
void Step ()
Public Attributes
double delta
double tdelta
Private Attributes
sf::Clock clock
Detailed Description
Definition at line 7 of file Time.h.
Member Function Documentation
void NLS::_Time::Reset ()
Definition at line 9 of file Time.cpp.
References clock, delta, and tdelta.
Referenced by NLS::Init().
                     {
    clock.Reset();
    delta = 0;
    tdelta = 0;
}
void NLS::_Time::Step ()
Definition at line 15 of file Time.cpp.
Referenced by NLS::Init(), and NLS::Loop().
                    {
    double temp = clock.GetElapsedTime();
    delta = temp-tdelta;
    tdelta = temp;
}
Member Data Documentation
sf::Clock NLS::_Time::clock [private]
Definition at line 8 of file Time.h.
Referenced by Reset().
double NLS::_Time::delta
Definition at line 12 of file Time.h.
Referenced by NLS::Loop(), Reset(), and NLS::View_::Step().
double NLS::_Time::tdelta
Definition at line 13 of file Time.h.
Referenced by NLS::Init(), and Reset().
The documentation for this class was generated from the following files:
NoLifeStory/Time.h
NoLifeStory/Time.cpp