NoLifeStory: Functions Namespace Reference
Functions Namespace Reference
Functions
bool help (const string &args)
Function Documentation
bool Functions::help (const string & args)
Definition at line 7 of file Functions.cpp.
References NLS::C(), CommandFunctions::CommandList, and CommandFunctions::showSyntax().
Referenced by CommandFunctions::initialize().
{
    using CommandFunctions::CommandList;
    if (args.length() != 0) {
        if (CommandList.find(args) != CommandList.end()) {
            CommandFunctions::showSyntax(args, true);
        }
        else {
            NLS::C("INFO") << "Command \"" << args << "\" does not exist." << endl;
        }
    }
    else {
        ostringstream strm;
        bool has = false;
        for (auto iter = CommandList.begin(); iter != CommandList.end(); iter++) {
            if (!has) {
                strm << "Available commands: ";
                has = true;
            }
            strm << iter->first << " ";
        }
        NLS::C("INFO") << strm.str() << endl;
    }
    return true;
}