NoLifeStory: NLS::WZ Namespace Reference
NLS::WZ Namespace Reference
Classes
class Image
class PNGProperty
class SoundProperty
Functions
void File (Node n)
void SubProperty (ifstream *file, Node n, uint32_t offset)
void ExtendedProperty (ifstream *file, Node n, uint32_t offset)
void Init (const string &path)
Variables
Node Top
Node Empty
Function Documentation
void NLS::WZ::ExtendedProperty (ifstream * file, Node n, uint32_t offset)
Definition at line 462 of file WZ.cpp.
References NLS::C(), NLS::Sprite::data, NLS::Node::data, NLS::Node::g(), NLS::SpriteData::originx, NLS::SpriteData::originy, NLS::SpriteData::png, ReadCInt(), ReadEncString(), ReadStringOffset(), NLS::NodeData::sprite, SubProperty(), and tostring().
Referenced by SubProperty().
{
    string name;
    uint8_t a = Read<uint8_t>(file);
    if (a == 0x1B) {
        int32_t inc = Read<int32_t>(file);
        uint32_t pos = offset+inc;
        uint32_t p = file->tellg();
        file->seekg(pos);
        name = ReadEncString(file);
        file->seekg(p);
    } else {
        name = ReadEncString(file);
    }
    if (name == "Property") {
        file->seekg(2, ios::cur);
        SubProperty(file, n, offset);
    } else if (name == "Canvas") {
        file->seekg(1, ios::cur);
        uint8_t b = Read<uint8_t>(file);
        if (b == 1) {
            file->seekg(2, ios::cur);
            SubProperty(file, n, offset);
        }
        n.data->sprite.data = new SpriteData;
        n.data->sprite.data->png = new PNGProperty(file, n.data->sprite);
        n.data->sprite.data->originx = n["origin"]["x"];
        n.data->sprite.data->originy = n["origin"]["y"];
    } else if (name == "Shape2D#Vector2D") {
        n.g("x") = ReadCInt(file);
        n.g("y") = ReadCInt(file);
    } else if (name == "Shape2D#Convex2D") {
        int32_t ec = ReadCInt(file);
        for (int i = 0; i < ec; i++) {
            ExtendedProperty(file, n.g(tostring(ec)), offset);
        }
    } else if (name == "Sound_DX8") {
        new SoundProperty(file, n);
    } else if (name == "UOL") {
        file->seekg(1, ios::cur);
        uint8_t b = Read<uint8_t>(file);
        switch (b) {
        case 0:
            n.g(name) = ReadEncString(file);
            break;
        case 1:
            {
                uint32_t off = Read<uint32_t>(file);
                n.g(name) = ReadStringOffset(file, offset+off);
                break;
            }
        default:
            C("ERROR") << "Unknown UOL type" << endl;
            throw(273);
        }
    } else {
        C("ERROR") << "Unknown ExtendedProperty type" << endl;
        throw(273);
    };
}
void NLS::WZ::File (Node n)
Definition at line 199 of file WZ.cpp.
References NLS::C(), NLS::Node::data, EncVersion, NLS::Node::g(), NLS::NodeData::name, OffsetKey, Path, ReadCInt(), ReadEncFast(), ReadEncString(), tostring(), Version, VersionHash, WZKey, and WZKeys.
Referenced by Init().
                       {
    string filename = Path+n.data->name+".wz";
    ifstream *file = new ifstream(filename, ios::in|ios::binary);
    if (!file->is_open()) {
        C("ERROR") << "Failed to load " << filename << endl;
        return;//Don't throw an error because of Nexon's stupid ExcelReport crap
    }
    string ident(4, '\0');
    file->read(const_cast<char*>(ident.c_str()), 4);
    if (ident != "PKG1") {
        C("ERROR") << "Invalid ident header for " << filename << endl;
        throw(273);
    }
    uint64_t fileSize = Read<uint64_t>(file);
    uint32_t fileStart = Read<uint32_t>(file);
    string copyright;
    *file >> copyright;
    file->seekg(fileStart);
    auto ReadOffset = [](ifstream* file, uint32_t fileStart) -> uint32_t {
        uint32_t p = file->tellg();
        p = (p-fileStart)^0xFFFFFFFF;
        p *= VersionHash;
        p -= OffsetKey;
        p = (p<<(p&0x1F))|(p>>(32-p&0x1F));
        uint32_t more = Read<uint32_t>(file);
        p ^= more;
        p += fileStart*2;
        return p;
    };
    if (!Version) {
        EncVersion = Read<int16_t>(file);
        int32_t count = ReadCInt(file);
        uint32_t c = 0;
        for (int k = 0; k < count; k++) {
            uint8_t type = Read<uint8_t>(file);
            if (type == 3) {
                ReadEncFast(file);
                ReadCInt(file);
                ReadCInt(file);
                Read<uint32_t>(file);
                continue;
            } else if (type == 4) {
                ReadEncFast(file);
                ReadCInt(file);
                ReadCInt(file);
                c = file->tellg();
                break;
            } else {
                C("ERROR") << "Malformed WZ structure" << endl;
                throw(273);
            }
        }
        if (c == 0) {
            C("ERROR") << "Unable to find a top level .img for hash verification" << endl;
            throw(273);
        }
        bool success = false;
        for (uint8_t j = 0; j < 2 and !success; j++) {
            WZKey = WZKeys[j];
            for (Version = 0; Version < 256; Version++) {
                string s = tostring(Version);
                VersionHash = 0;
                for (int i = 0; i < s.size(); i++) {
                    VersionHash = 32*VersionHash+s[i]+1;
                }
                uint32_t result = 0xFF^(VersionHash>>24)^(VersionHash<<8>>24)^(VersionHash<<16>>24)^(VersionHash<<24>>24);
                if (result == EncVersion) {
                    file->clear();
                    file->seekg(c);
                    uint32_t offset = ReadOffset(file, fileStart);
                    if (offset > fileSize) {
                        continue;
                    }
                    file->seekg(offset);
                    uint8_t a = Read<uint8_t>(file);
                    if(a != 0x73) {
                        continue;
                    }
                    string ss = ReadEncString(file);
                    if (ss != "Property") {
                        continue;
                    }
                    C("WZ") << "Detected WZ version: " << Version << endl;
                    success = true;
                    break;
                }
            }
        }
        if (!success) {
            C("ERROR") << "Unable to determine WZ version" << endl;
            throw(273);
        }
        file->seekg(fileStart+2);
    } else {
        int16_t eversion = Read<int16_t>(file);
        if (eversion != EncVersion) {
            C("ERROR") << "Version of WZ file does not match existing files" << endl;
            throw(273);
        }
    }
    function <void(Node n)> Directory = [&](Node n) {
        int32_t count = ReadCInt(file);
        if (count == 0) {
            File(n);
            return;
        }
        set<pair<string, uint32_t>> dirs;
        for (int i = 0; i < count; i++) {
            string name;
            uint8_t type = Read<uint8_t>(file);
            if (type == 1) {
                file->seekg(10, ios::cur);
                continue;
            } else if (type == 2) {
                int32_t s = Read<int32_t>(file);
                uint32_t p = file->tellg();
                file->seekg(fileStart+s);
                type = Read<uint8_t>(file);
                name = ReadEncString(file);
                file->seekg(p);
            } else if (type == 3) {
                name = ReadEncString(file);
            } else if (type == 4) {
                name = ReadEncString(file);
            } else {
                C("ERROR") << "Wat?" << endl;
                throw(273);
            }
            int32_t fsize = ReadCInt(file);
            int32_t checksum = ReadCInt(file);
            uint32_t offset = ReadOffset(file, fileStart);
            if (type == 3) {
                dirs.insert(pair<string, uint32_t>(name, offset));
            } else if (type == 4) {
                name.erase(name.size()-4);
                new Image(file, n.g(name), offset);
            } else {
                C("ERROR") << "Wat?" << endl;
                throw(273);
            }
        }
        for (auto it = dirs.begin(); it != dirs.end(); it++) {
            file->seekg(it->second);
            Directory(n.g(it->first));
        }
    };
    Directory(n);
}
void NLS::WZ::Init (const string & path)
Definition at line 174 of file WZ.cpp.
References BMSKey, NLS::C(), NLS::Node::data, exists(), File(), NLS::NodeData::name, Path, and Top.
{
    memset(BMSKey, 0, 0xFFFF);
    Top.data = new NodeData();
    string paths[5] = {path, "", "C:/Nexon/MapleStory/", "/", "T:/"};
    for (int i = 0; i < 5; i++) {
        Path = paths[i];
        if (exists(Path+"Data.wz")) {
            C("WZ") << "Loading beta WZ file structure" << endl;
            Top.data->name = "Data";
            File(Top);
            return;
        }
        if(exists(Path+"Base.wz")) {
            C("WZ") << "Loading standard WZ file structure" << endl;
            Top.data->name = "Base";
            File(Top);
            return;
        }
    }
    C("ERROR") << "I CAN'T FIND YOUR WZ FILES YOU NUB" << endl;
    throw(273);
}
void NLS::WZ::SubProperty (ifstream * file, Node n, uint32_t offset)
Definition at line 420 of file WZ.cpp.
References NLS::C(), ExtendedProperty(), NLS::Node::g(), ReadCInt(), and ReadString().
Referenced by ExtendedProperty(), and NLS::WZ::Image::Parse().
{
    int32_t count = ReadCInt(file);
    for (int i = 0; i < count; i++) {
        string name = ReadString(file, offset);
        uint8_t a = Read<uint8_t>(file);
        switch (a) {
        case 0x00:
            n.g(name);
            break;
        case 0x0B:
        case 0x02:
            n.g(name) = Read<uint16_t>(file);
            break;
        case 0x03:
            n.g(name) = ReadCInt(file);
            break;
        case 0x04:
            if (Read<uint8_t>(file) == 0x80) {
                n.g(name) = Read<float>(file);
            }
            break;
        case 0x05:
                n.g(name) = Read<double>(file);;
                break;
        case 0x08:
            n.g(name) = ReadString(file, offset);
            break;
        case 0x09:
            {
                uint32_t temp = Read<uint32_t>(file);
                temp += file->tellg();
                ExtendedProperty(file, n.g(name), offset);
                file->seekg(temp);
                break;
            }
        default:
            C("ERROR") << "Unknown Property type" << endl;
            throw(273);
        }
    }
}
Variable Documentation
NLS::Node NLS::WZ::Empty
Definition at line 11 of file WZ.cpp.
Referenced by NLS::Node::operator[]().
NLS::Node NLS::WZ::Top
Definition at line 10 of file WZ.cpp.
Referenced by Init(), NLS::Map::Load(), NLS::Tile::Load(), NLS::Portal::Load(), NLS::Back::Load(), and NLS::Obj::Load().