NoLifeStory: NLS::Map Namespace Reference
NLS::Map Namespace Reference
Classes
class Layer
Functions
void Load (const string &id, const string &portal)
void Load ()
void Draw ()
Variables
Node node
string nextmap
string nextportal
string curmap
vector< Back * > Backgrounds
Layer Layers [8]
vector< Back * > Foregrounds
Sound bgmusic
Function Documentation
void NLS::Map::Draw ()
Definition at line 88 of file Map.cpp.
References Backgrounds, NLS::Map::Layer::Draw(), Foregrounds, and Layers.
                  {
    for (uint32_t i = 0; i < Backgrounds.size(); i++) {
        Backgrounds[i]->Draw();
    }
    for (uint8_t i = 0; i < 8; i++) {
        Layers[i].Draw();
    }
    for (uint32_t i = 0; i < Portal::Portals.size(); i++) {
        Portal::Portals[i]->Draw();
    }
    for (uint32_t i = 0; i < Foregrounds.size(); i++) {
        Foregrounds[i]->Draw();
    }
}
void NLS::Map::Load (const string & id, const string & portal)
Definition at line 16 of file Map.cpp.
References nextmap, and nextportal.
Referenced by NLS::Console::HandleCommand(), NLS::Init(), and Load().
{
    nextmap = id;
    nextportal = portal;
}
void NLS::Map::Load ()
Definition at line 21 of file Map.cpp.
References Backgrounds, bgmusic, NLS::C(), curmap, NLS::footholds, Foregrounds, NLS::_View::height, Layers, Load(), nextmap, nextportal, node, NLS::Map::Layer::Objs, NLS::Sound::Play(), NLS::_Time::Reset(), NLS::Map::Layer::Tiles, NLS::Time, NLS::WZ::Top, NLS::_View::tx, NLS::_View::ty, NLS::Unload(), NLS::View, NLS::_View::xmax, NLS::_View::xmin, NLS::_View::ymax, and NLS::_View::ymin.
                  {
    if (curmap == nextmap) {
        C("ERROR") << "The specified map is already loaded" << endl;
        nextmap = "";
        return;
    }
    if (nextmap == "MapLogin") {
        node = WZ::Top["UI"]["MapLogin"];
        //throw(273);
    } else {
        if (nextmap.size() < 9) {
            nextmap.insert(0, 9-nextmap.size(), '0');
        }
        char zone = nextmap[0];
        node = WZ::Top["Map"]["Map"][string("Map")+zone][nextmap];
    }
    if (!node) {
        C("ERROR") << "Unable to locate map " << nextmap << endl;
        nextmap = "";
        nextportal = "";
        return;
    }
    Time.Reset();
    curmap = nextmap;
    C("INFO") << "Loading map " << nextmap << endl;
    string bgm = node["info"]["bgm"];
    auto p = bgm.find('/');
    bgmusic = WZ::Top["Sound"][bgm.substr(0, p)][bgm.substr(p+1)];
    bgmusic.Play(true);
    for (uint8_t i = 0; i < 8; i++) {
        Layers[i].Tiles.clear();
        Layers[i].Objs.clear();
    }
    Backgrounds.clear();
    Foregrounds.clear();
    Sprite::Unload();
    Foothold::Load(node);
    Tile::Load(node);
    Obj::Load(node);
    Back::Load(node);
    Portal::Load(node);
    Reactor::Load(node);
    View.tx = 0;
    View.ty = 0;
    if (node["info"]["VRLeft"]) {
        View.xmin = node["info"]["VRLeft"];
        View.xmax = node["info"]["VRRight"];
        View.ymin = node["info"]["VRTop"];
        View.ymax = node["info"]["VRBottom"];
    } else {
        View.xmin = 1000000;
        View.xmax = -1000000;
        View.ymin = 1000000;
        View.ymax = -1000000;
        for (auto it = footholds.begin(); it != footholds.end(); it++) {
            View.xmin = min(min(View.xmin, (*it)->x1), (*it)->x2);
            View.ymin = min(min(View.ymin, (*it)->y1), (*it)->y2);
            View.xmax = max(max(View.xmax, (*it)->x1), (*it)->x2);
            View.ymax = max(max(View.ymax, (*it)->y1), (*it)->y2);
        }
        View.ymax += 128;
        View.ymin -= View.height;
    }
    nextmap = "";
    nextportal = "";
}
Variable Documentation
vector< NLS::Back * > NLS::Map::Backgrounds
Definition at line 11 of file Map.cpp.
Referenced by Draw(), NLS::Back::Load(), and Load().
NLS::Sound NLS::Map::bgmusic
Definition at line 14 of file Map.cpp.
Referenced by Load().
string NLS::Map::curmap
Definition at line 9 of file Map.cpp.
Referenced by Load().
vector< NLS::Back * > NLS::Map::Foregrounds
Definition at line 13 of file Map.cpp.
Referenced by Draw(), NLS::Back::Load(), and Load().
NLS::Map::Layer NLS::Map::Layers
Definition at line 12 of file Map.cpp.
Referenced by Draw(), NLS::Tile::Load(), Load(), and NLS::Obj::Load().
string NLS::Map::nextmap
Definition at line 8 of file Map.cpp.
Referenced by Load().
string NLS::Map::nextportal
Definition at line 10 of file Map.cpp.
Referenced by Load().
NLS::Node NLS::Map::node
Definition at line 7 of file Map.cpp.
Referenced by Load().