NoLifeStory: NLS::Graphics Namespace Reference
NLS::Graphics Namespace Reference
Functions
void Init ()
void Draw ()
void Unload ()
Function Documentation
void NLS::Graphics::Draw ()
Definition at line 34 of file Graphics.cpp.
References NLS::C(), NLS::View_::Step(), NLS::View, and NLS::window.
Referenced by NLS::Loop().
                       {
    glClear(GL_COLOR_BUFFER_BIT);
    View.Step();
    Map::Draw();
    Foothold::Draw();
    window->Display();
    switch (glGetError()) {
    case GL_NO_ERROR:
        break;
    default:
        C("ERROR") << "OH GOD OPENGL FAILED" << endl;
    }
}
void NLS::Graphics::Init ()
Definition at line 9 of file Graphics.cpp.
References IDI_NOLIFESTORY_ICON, and NLS::window.
                       {
    window = new sf::Window(sf::VideoMode(800, 600), "NoLifeStory::Loading", sf::Style::Titlebar, sf::ContextSettings(0, 0, 0, 2, 0));
#ifdef NLS_WINDOWS
    HANDLE hIcon = LoadIconW(GetModuleHandleW(NULL), MAKEINTRESOURCEW(IDI_NOLIFESTORY_ICON));
    HWND hWnd = window->GetSystemHandle();
    if (hWnd) {
        ::SendMessageW(hWnd, WM_SETICON, ICON_SMALL, (LPARAM) hIcon);
    }
#endif
    window->ShowMouseCursor(false);
    window->EnableKeyRepeat(true);
    glClearColor(0, 0, 0, 0);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glEnable(GL_BLEND);
    glEnable(GL_TEXTURE_2D);
    glDisable(GL_DEPTH_TEST);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    glOrtho(0, 800, 600, 0, -1, 1);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    glClear(GL_COLOR_BUFFER_BIT);
    window->Display();
}
void NLS::Graphics::Unload ()