NoLifeStory: NLS Namespace Reference
NLS Namespace Reference
Namespaces
namespace Graphics
namespace Map
namespace Network
namespace WZ
Classes
class LoginServer
class WorldServer
class AniSprite
class Back
class Console
class Stream
class Foothold
class Obj
class Portal
class Reactor
class Sound
class SpriteData
class Sprite
class Tile
class _Time
class _View
class Node
class NodeData
Functions
void Init (vector< string > args)
void Loop ()
void Unload ()
void Init (const vector< string > &args)
void LoadConfig ()
Stream & C (const string &type)
Variables
Console * console
set< Foothold * > footholds
sf::Window * window = 0
class NLS::_Time Time
class NLS::_View View
Function Documentation
Stream& NLS::C (const string & type) [inline]
Definition at line 51 of file Console.h.
Referenced by Decompress(), NLS::Back::Draw(), NLS::Graphics::Draw(), NLS::WZ::ExtendedProperty(), NLS::WZ::File(), CommandFunctions::handleCommand(), Functions::help(), Init(), NLS::Network::Init(), NLS::WZ::Init(), NLS::Reactor::Load(), NLS::Map::Load(), NLS::Back::Load(), NLS::Foothold::Load(), NLS::WZ::Image::Parse(), NLS::WZ::PNGProperty::Parse(), NLS::WZ::PNGProperty::PNGProperty(), CommandFunctions::showSyntax(), NLS::_Time::Step(), and NLS::WZ::SubProperty().
{
        static Stream s;
        s << endl;
        s << type << ": ";
        return s;
    }
void NLS::Init (vector< string > args)
Definition at line 9 of file Server.cpp.
Referenced by Init(), and main().
{
    LoginServer::Start();
    WorldServer::Start();
    cout << "INFO: NoLifeServer is up and running" << endl;
}
void NLS::Init (const vector< string > & args)
Definition at line 12 of file Client.cpp.
References C(), Init(), NLS::Map::Load(), NLS::_Time::Reset(), NLS::_Time::Step(), Time, and window.
{
    C("INFO") << "Initializing NoLifeStory" << endl;
    Network::Init();
    Time.Reset();
    WZ::Init(args.size()>1?args[1]:"");
    Time.Step();
    Graphics::Init();
    BASS_Init(-1, 44100, 0, window->GetSystemHandle(), 0);
    Map::Load("100000000", "");
    Map::Load();
}
void NLS::LoadConfig ()
bool NLS::Loop ()
Definition at line 15 of file Server.cpp.
Referenced by NLS::LoginServer::LoginServer(), main(), and NLS::WorldServer::WorldServer().
               {
    auto GetCommand = []()->vector<string>{
        string command;
        char cstr[1024];
        cin.getline(cstr,1024);
        command = cstr;
        istringstream iss(command);
        vector<string> words;
        copy(istream_iterator<string>(iss), istream_iterator<string>(), back_inserter<vector<string>>(words));
        return words;
    };
    while (true) {
        vector<string> command = GetCommand();
        if (command.size() == 0) {
            continue;
        } else if (command[0] == "help" or command[0] == "?") {
            if (command.size() > 1) {
                if (command[1] == "shutdown") {
                    cout << "HELP: Shuts down NoLifeServer gracefully, preserving all data" << endl;
                } else if (command[1] == "forceshutdown") {
                    cout << "HELP: Forces NoLifeServer to shutdown immediately, losing any temporary data" << endl;
                } else if (command[1] == "help" or command[1] == "?") {
                    cout << "HELP: Displays information on commands available and what each command does" << endl;
                }
            } else {
                cout << "HELP: Available commands: help, ?, shutdown, forceshutdown" << endl;
                cout << "HELP: Enter \"help command\" for help with a particular command" << endl;
            }
        } else if (command[0] == "shutdown") {
            return;
        } else if (command[0] == "forceshutdown") {
            cout << "INFO: Forcing NoLifeServer shutdown" << endl;
            exit(1);
        } else {
            cout << "INFO: Unknown command: " << command[0] << endl;
        }
    }
    return;
}
void NLS::Unload ()
Definition at line 55 of file Server.cpp.
Referenced by NLS::Map::Load(), and main().
                 {
    cout << "INFO: Initiating NoLifeServer shutdown" << endl;
    LoginServer::Shutdown();
    WorldServer::Shutdown();
    cout << "INFO: NoLifeServer shutdown complete" << endl;
    system("pause");
}
Variable Documentation
NLS::Console * NLS::console
Definition at line 7 of file Console.cpp.
Referenced by main(), and NLS::Stream::operator<<().
set< NLS::Foothold * > NLS::footholds
Definition at line 7 of file Foothold.cpp.
Referenced by NLS::Foothold::Draw(), NLS::Map::Load(), and NLS::Foothold::Load().
NLS::_Time NLS::Time
Definition at line 7 of file Time.cpp.
Referenced by NLS::Back::Draw(), NLS::Obj::Draw(), NLS::Graphics::Draw(), Init(), NLS::Map::Load(), NLS::AniSprite::Step(), and NLS::_View::Step().
NLS::_View NLS::View
Definition at line 7 of file View.cpp.
Referenced by NLS::Back::Draw(), NLS::Obj::Draw(), NLS::Graphics::Draw(), NLS::Sprite::Draw(), NLS::Map::Load(), and NLS::Console::Loop().
sf::Window * NLS::window = 0
Definition at line 7 of file Graphics.cpp.
Referenced by NLS::Graphics::Draw(), Init(), NLS::Graphics::Init(), and NLS::Console::Loop().